### PR TITLE
SCT-1486 Update direct feeds notifier for feeds API changes

### PR DESCRIPTION
**Pull request by MrCreosote**
Kafka notifier next

### CODE REVIEW

**Comment by MrCreosote** [comment]
Ok, I'm merging. let me know when you have feeds updated on CI and I'll test.

**Comment by briehl** [comment]
It's up. Go for it.

**Comment by briehl** [comment]
Just not with the App or Service types yet.

**Comment by MrCreosote** [comment]
@briehl most of the operations use the service type, unfortunately. It probably makes sense for me to hold off until that's up.

**Pull request merged**
